server:
  port: 8080
mysql:
  host: "localhost"
  port: 3306
  dbName: "test_db"
  username: "admin"
  password: "admin@123"
jwt:
  exp: 3600
  iss: "ipfs-library-server"
  signKey: "qaz123wsx345edc678rfv890"